---
# Organization to pull metrics from (must be an array)
organization: ['brainglobe', 'neuroinformatics-unit']

# Start date to pull metrics from
since: '2018-01-02'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/dashboard'
